pipeline:
  download:
    image: docker.io/fedora
    commands:
      - curl https://builds.matomo.org/piwik-3.4.0.tar.gz > piwik.tar.gz
      - tar xvf piwik.tar.gz --strip 1 -C root/matomo
  docker:
    image: docker.io/plugins/docker
    repo: docker.jcg.re/matomo
    registry: docker.jcg.re
    secrets: [ docker_username, docker_password ]
    auto_tag: true
